# Generated by Django 3.1.2 on 2020-11-22 20:02

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text representation of answer option')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=(core.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PoolAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pool')),
            ],
        ),
        migrations.CreateModel(
            name='PoolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('anonymous', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('open', 'Open (Free answer)'), ('closed', 'Closed (Fixed answer options)')], default='closed', max_length=16)),
            ],
            bases=(core.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamsTeam',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsUser',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answeroption')),
                ('pool_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poolanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pooluser')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsChannel',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teamsteam')),
            ],
        ),
        migrations.CreateModel(
            name='PoolToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('one_time', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pool')),
            ],
        ),
        migrations.AddField(
            model_name='poolanswer',
            name='pool_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pooltoken'),
        ),
        migrations.AddField(
            model_name='poolanswer',
            name='teams_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teamschannel'),
        ),
        migrations.AddField(
            model_name='poolanswer',
            name='teams_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teamsuser'),
        ),
        migrations.AddField(
            model_name='pool',
            name='questions',
            field=models.ManyToManyField(to='core.Question'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question'),
        ),
    ]
